name: pullora
services:
  pullora:
    image: ghcr.io/maroishiku/pullora:latest
    container_name: pullora
    restart: unless-stopped
    ports:
      - target: 8080
        published: "8180"
        protocol: tcp
    environment:
      APP_DATA_DIR: /data
      DOWNLOAD_DIR: /downloads
      FIRST_ADMIN_USERNAME: admin
      FIRST_ADMIN_PASSWORD_FILE: /run/secrets/first_admin_password
      SESSION_DAYS: 14
      TZ: Europe/Berlin
    volumes:
      - type: bind
        source: /media/ZimaOS-HD/AppData/pullora/data
        target: /data
      - type: bind
        source: /media/ZimaOS-HD/AppData/pullora/downloads
        target: /downloads
    secrets:
      - first_admin_password
    network_mode: bridge
    privileged: false
    labels:
      icon: https://raw.githubusercontent.com/MaroIshiku/Pullora/main/app/static/pullora-logo.png

secrets:
  first_admin_password:
    file: /media/ZimaOS-HD/AppData/pullora/secrets/admin_password.txt

x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://raw.githubusercontent.com/MaroIshiku/Pullora/main/app/static/pullora-logo.png
  index: /
  is_uncontrolled: false
  port_map: "8180"
  scheme: http
  store_app_id: pullora
  title:
    custom: Pullora
    en_us: Pullora
